# Generated by Django 5.0.4 on 2024-05-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_remove_cadastro_id_alter_cadastro_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.CharField(max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
