# Generated by Django 5.0.4 on 2024-05-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0004_alter_cadastro_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='nome_usuario',
            new_name='username',
        ),
    ]
