# Generated by Django 5.0.4 on 2024-05-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0008_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
