# Generated by Django 5.0.4 on 2024-05-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0010_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
