# Generated by Django 5.0.4 on 2024-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0012_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='name',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
