# Generated by Django 5.0.4 on 2024-05-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0014_cursos_unb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cursos_unb',
        ),
    ]
