# Generated by Django 5.0.4 on 2024-06-01 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0018_cursos_unb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos_unb',
            name='pessoas',
        ),
        migrations.AddField(
            model_name='cursos_unb',
            name='avaliadores',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
