# Generated by Django 5.0.4 on 2024-06-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0020_rename_avaliadores_cursos_unb_cursantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
