# Generated by Django 5.0.4 on 2024-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0021_alter_cadastro_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='privacidade',
            field=models.BooleanField(default=True),
        ),
    ]
