# Generated by Django 5.0.4 on 2024-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0022_perfilusuario_foto_perfilusuario_privacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='senha_confirma',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
