# Generated by Django 5.0.4 on 2024-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0023_cadastro_senha_confirma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username_Trocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_antigo', models.CharField(max_length=15)),
                ('novo_username', models.CharField(max_length=15)),
                ('dia_trocado', models.CharField(max_length=100)),
            ],
        ),
    ]
