# Generated by Django 5.0.4 on 2024-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0024_username_trocado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username_trocado',
            name='dia_trocado',
            field=models.DateTimeField(),
        ),
    ]
