# Generated by Django 5.0.4 on 2024-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0026_remove_username_trocado_dia_trocado'),
    ]

    operations = [
        migrations.AddField(
            model_name='username_trocado',
            name='dia_dia',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
