# Generated by Django 5.0.4 on 2024-06-24 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0027_username_trocado_dia_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username_trocado',
            name='dia_dia',
        ),
        migrations.AddField(
            model_name='username_trocado',
            name='data_troca',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='username_trocado',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='username_trocado',
            name='novo_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='username_trocado',
            name='username_antigo',
            field=models.CharField(max_length=150),
        ),
    ]
