# Generated by Django 4.2 on 2024-07-14 19:04

import app_cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0029_senha_trocada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.UUIDField(default=app_cadastro.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
