# Generated by Django 5.0.4 on 2024-07-18 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0030_alter_passwordresettoken_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_deletados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_deletado', models.EmailField(max_length=254)),
                ('username_deletado', models.CharField(max_length=15)),
                ('data_deletado', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_deletado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
