# Generated by Django 5.0.4 on 2024-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0031_usuarios_deletados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_deletados',
            name='user_deletado',
        ),
        migrations.RemoveField(
            model_name='usuarios_deletados',
            name='username_deletado',
        ),
        migrations.AlterField(
            model_name='usuarios_deletados',
            name='email_deletado',
            field=models.CharField(max_length=50),
        ),
    ]
