# Generated by Django 5.0.4 on 2024-04-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nick', models.CharField(max_length=100)),
                ('autor_email', models.EmailField(max_length=254)),
                ('hora_publicacao', models.TimeField()),
                ('texto', models.CharField(max_length=250)),
                ('curtidas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliação_1', models.FloatField()),
                ('avaliação_2', models.FloatField()),
                ('avaliação_3', models.FloatField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.professor')),
            ],
        ),
    ]
