# Generated by Django 5.0.4 on 2024-04-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carga_horaria',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
