# Generated by Django 5.0.4 on 2024-05-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_remove_materia_carga_horaria_turma_local_turma_turno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='autor_email',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor_nick',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='curtidas',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='avaliação_1',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='avaliação_2',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='avaliação_3',
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='turma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materias.turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='aprovacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='reprovado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turma',
            name='avaliacao_apoio_aluno',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='turma',
            name='avaliacao_didatica',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='turma',
            name='avaliacao_dificuldade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='turma',
            name='avaliadores',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
