# Generated by Django 5.0.4 on 2024-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_remove_comentario_autor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='atividades',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='turma',
            name='resumos',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='turma',
            name='videos',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
