# Generated by Django 5.0.4 on 2024-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_turma_atividades_turma_resumos_turma_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='numero_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
