# Generated by Django 5.0.4 on 2024-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_turma_numero_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='avaliacao_apoio_aluno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turma',
            name='avaliacao_didatica',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turma',
            name='avaliacao_dificuldade',
            field=models.IntegerField(default=0),
        ),
    ]
