# Generated by Django 5.0.4 on 2024-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0007_alter_turma_avaliacao_apoio_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='hora_publicacao',
            field=models.DateTimeField(),
        ),
    ]
