# Generated by Django 5.0.4 on 2024-05-20 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0008_alter_comentario_hora_publicacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='reprovado',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='aprovacoes',
        ),
        migrations.AddField(
            model_name='professor',
            name='aprovacoes',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
