# Generated by Django 5.0.4 on 2024-05-24 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0009_remove_professor_reprovado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='curtidas',
            field=models.ManyToManyField(related_name='curtida', to=settings.AUTH_USER_MODEL),
        ),
    ]
