# Generated by Django 5.0.4 on 2024-05-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0010_comentario_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='denuncia',
            field=models.IntegerField(default=0),
        ),
    ]
