# Generated by Django 5.0.4 on 2024-06-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0011_comentario_denuncia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='resumos',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='videos',
        ),
    ]
