# Generated by Django 5.0.6 on 2024-06-03 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0012_remove_turma_atividades_remove_turma_resumos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='denuncia',
        ),
        migrations.AddField(
            model_name='comentario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_ofensivo', models.BooleanField()),
                ('info_falsa', models.BooleanField()),
                ('bullyng', models.BooleanField()),
                ('cont_sexual', models.BooleanField()),
                ('discurso_odio', models.BooleanField()),
                ('observacao', models.CharField(max_length=250)),
                ('hora_publicacao', models.DateTimeField()),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.comentario')),
            ],
        ),
    ]
