# Generated by Django 5.0.6 on 2024-06-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0013_remove_comentario_denuncia_comentario_ativo_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='bullyng',
            new_name='bullying',
        ),
    ]
