# Generated by Django 5.0.4 on 2024-06-05 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0014_rename_bullyng_report_bullying'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_publicacao', models.DateTimeField()),
                ('titulo', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=250)),
                ('ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curtidas', models.ManyToManyField(related_name='curtida_atividades', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materias.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_publicacao', models.DateTimeField()),
                ('titulo', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=250)),
                ('ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curtidas', models.ManyToManyField(related_name='curtida_resumo', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materias.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_publicacao', models.DateTimeField()),
                ('titulo', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=250)),
                ('ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curtidas', models.ManyToManyField(related_name='curtida_videos', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materias.turma')),
            ],
        ),
    ]
