# Generated by Django 5.0.4 on 2024-06-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0016_alter_comentario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
