# Generated by Django 5.0.4 on 2024-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0017_alter_comentario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_deletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=250)),
                ('dia_deletado', models.CharField(max_length=100)),
            ],
        ),
    ]
