# Generated by Django 5.0.4 on 2024-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0019_comentario_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='indentificacao',
            field=models.IntegerField(default=0),
        ),
    ]
