# Generated by Django 5.0.4 on 2024-07-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0020_comentario_indentificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_editado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('texto_antigo', models.CharField(max_length=450)),
                ('texto_novo', models.CharField(max_length=450)),
                ('dia_editado', models.CharField(max_length=100)),
            ],
        ),
    ]
