# Generated by Django 5.0.4 on 2024-07-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0021_comentario_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
