# Generated by Django 5.0.7 on 2024-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0022_comentario_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome_professor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
