# Generated by Django 5.0.7 on 2024-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0022_comentario_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.CharField(default='2024.1', max_length=6),
        ),
    ]
