# Generated by Django 5.0.7 on 2024-08-06 14:10

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Professor = apps.get_model('materias', 'Professor')
    Turma = apps.get_model('materias', 'Turma')
    for t in Turma.objects.all():
        t.nome_professor = t.professor.nome
        t.save()

def popula_info(apps, schema_editor):
    Turma = apps.get_model('materias', 'Turma')
    info = apps.get_model('materias', 'Info_semestre')
    for t in Turma.objects.all():
        info.objects.create(turma=t, local=t.local, turno=t.turno)


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0023_remove_turma_professor_turma_nome_professor_and_more'),
    ]

    operations = [
        migrations.RunPython(combine_names),
        migrations.RunPython(popula_info)
    ]
