# Generated by Django 5.0.7 on 2024-08-06 13:15

from django.db import migrations, models


def add_professores():
    for t in Turma.object.all():
            t.professores.add(Professor.objects.get(t.professor.nome))
            t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0023_turma_nome_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(to='materias.professor'),
        ),

        migrations.RunPython(add_professores),
        
        
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
    ]
