# Generated by Django 5.0.7 on 2024-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0024_auto_20240806_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(to='materias.professor'),
        ),
    ]
