# Generated by Django 5.0.7 on 2024-08-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0024_remove_turma_professor_turma_professores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='professores',
            new_name='professor',
        ),
    ]
