# Generated by Django 5.0.7 on 2024-08-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0025_rename_professores_turma_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(default='NA', max_length=30)),
                ('local', models.CharField(default='NA', max_length=30)),
                ('semestre', models.CharField(default='2024.1', max_length=6)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.turma')),
            ],
        ),
    ]
