# Generated by Django 5.0.7 on 2024-08-06 14:20

from django.db import migrations

def add_professores(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Professor = apps.get_model('materias', 'Professor')
    Turma = apps.get_model('materias', 'Turma')
    for t in Turma.objects.all():
        prof = Professor.objects.get(nome=t.nome_professor)
        t.professores.add(prof)
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0025_remove_turma_professor_turma_professores'),
    ]

    operations = [
        migrations.RunPython(add_professores)
    ]
