# Generated by Django 5.0.7 on 2024-08-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0026_auto_20240806_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='professores',
            new_name='professor',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='local',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='nome_professor',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='turno',
        ),
    ]
