# Generated by Django 5.1.1 on 2024-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0029_auto_20240806_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Texto', models.CharField(max_length=1000)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
