# Generated by Django 5.1.1 on 2024-09-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0030_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Texto',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
